objects/My_Image__c/My_Image__c.object-meta.xml
<CustomObject>
    <description>Object to store picture with description, album and name</description>
    <label>My Image</label>
    <nameField>
        <label>Image</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/My_Image__c/fields/Album_number__c.field-meta.xml
<CustomField>
    <fullName>Album_number__c</fullName>
    <description>Album number from original data base</description>
    <label>Album number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/My_Image__c/fields/Image_Number__c.field-meta.xml
<CustomField>
    <fullName>Image_Number__c</fullName>
    <description>Image numer from original data base</description>
    <label>Image Number</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

objects/My_Image__c/fields/Miniature_Picture__c.field-meta.xml
<CustomField>
    <fullName>Miniature_Picture__c</fullName>
    <description>thumbnail URL for original pic</description>
    <label>Miniature Picture</label>
    <type>Url</type>
</CustomField>

objects/My_Image__c/fields/Picture_ID__c.field-meta.xml
<CustomField>
    <fullName>Picture_ID__c</fullName>
    <description>pic id from attachment</description>
    <label>Picture ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/My_Image__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <description>Original picture URL</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

objects/My_Image__c/fields/Thumbnail__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail__c</fullName>
    <formula>IMAGE(&#39;/servlet/servlet.FileDownload?file=&#39; + Thumbnail_ID__c, Thumbnail_ID__c, 20, 20)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Thumbnail</label>
    <type>Text</type>
</CustomField>

classes/MyImageController.cls
public with sharing class MyImageController {
    
    @AuraEnabled
    public static List<My_Image__c> getAllImages(String titleString){
        String filteredKey = sanitizeQueryString(titleString);
        return [Select id, name, title__c, Album_number__c,Image_Number__c, Miniature_Picture__c, Picture_ID__c, Picture_URL__c, Thumbnail__c FROM My_Image__c WHERE title__c!=null AND title__c LIKE:filteredKey LIMIT 30];
        
    }

    static String sanitizeQueryString(String aQuery) {
        if (aQuery == null) {
            return '%';
        }
        String trimmedQuery = aQuery.trim();
        if (trimmedQuery.length() == 0) return '%';
    
        return '%' + trimmedQuery.replaceAll('\\W+', '%') + '%';
    }
}